version: '3'

services:
  # FROM: https://hub.docker.com/r/roribio16/alpine-sqs/
  alpine-sqs:
    image: roribio16/alpine-sqs:latest
    container_name: alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
